### ISSUE TITLE
Preserve formatting in Notes app textarea

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Productivity-App#4] opened 2023-09-26 17:16 UTC
The textarea in the Notes App does not support any line breaks or extra formatting by default. Try to apply a solution which preserves the formatting when the note is saved and viewed by the user later.

**Comment by mhamzanadeem** [comment] 2023-09-26 17:18
I want to contribute to this issue . can u assign it to me

**Comment by mhamzanadeem** [comment] 2023-09-26 17:54
The problem in your App is not saving the notes. 
So should I work on this issue "saving the notes".
Or the problem is something else ?

**Comment by swagatmitra-b** [comment] 2023-09-26 18:04
Could you please explain what exactly the problem is?

**Comment by mhamzanadeem** [comment] 2023-09-26 18:10
**The problem is** :

when we click on " new note ",  it creates  a new note ,  but it didnt display on view side 
![77](https://github.com/swagatmitra-b/Productivity-App/assets/114602354/693b455c-dbf8-48e2-b0d1-811e96bc07f2)

(in short)The app is not not able to select a new note 

**Solution:** 
According to me ,  We have to work on feature " saving a new note ",  so the app  should be able to save the new note .
It can be done by  making local storage API.

**Comment by swagatmitra-b** [comment] 2023-09-26 18:17
You need to click on the note and then press the "Alt" key on your keyboard to save the note.

**Comment by mhamzanadeem** [comment] 2023-09-26 18:20
> You need to click on the note and then press the "Alt" key on your keyboard to save the note.

plz add this instruction to the contributing file ,

**Comment by swagatmitra-b** [comment] 2023-09-26 18:22
Please read the README file first

**Comment by mhamzanadeem** [comment] 2023-09-26 18:22
> The textarea in the Notes App does not support any line breaks or extra formatting by default. Try to apply a solution which preserves the formatting when the note is saved and viewed by the user later.

you are asking to implemet a feature in your app like "Bold the text", "Underline the text" ,  "Changing the font size"

**Comment by mhamzanadeem** [comment] 2023-09-26 18:23
> Please read the README file first

sorry my bad

**Comment by swagatmitra-b** [comment] 2023-09-26 18:29
That would be quite impressive if you can achieve that. But what I initially meant is that if you create a list of words on separate lines like so

word 1
word 2 
word 3

and save the note, the note will appear like this when viewed later. 

word1 word2 word3

You need to try to preserve the line breaks.

**Comment by mhamzanadeem** [comment] 2023-09-26 18:55
Have I fixed  the issue  ?  should i do pull request ?  


https://github.com/swagatmitra-b/Productivity-App/assets/114602354/7fbfed08-f79f-4c77-8799-1be1d633a929

**Comment by mhamzanadeem** [comment] 2023-09-26 19:00
Have I fixed the bug according to your expectation ? Should I do pull request ? If yes ,  can u tell what are the requirements by hactoberfest 2023 pull request.

https://github.com/swagatmitra-b/Productivity-App/assets/114602354/8a3d3624-4847-4673-87e6-712553befc65

**Comment by swagatmitra-b** [comment] 2023-09-26 19:03
Yes, congratulations! You can make the PR. I will merge it in October for your contribution to count.

**Closed as completed** 2023-09-26 19:27 UTC
Labels: enhancement, hacktoberfest
